config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :jobs
  root 'home#index'
  devise_for :users
  resources :conversations do
    resources :messages
   end
  get '/developers', to: "home#developers"
  mount SimpleDiscussion::Engine => "/forum"
  put 'jobs/:id/publish', to: "jobs#publish", as: "publish"
  put 'jobs/:id/unpublish', to: "jobs#unpublish", as: "unpublish"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/profile.rb
# == Schema Information
#
# Table name: profiles
#
#  id                 :bigint           not null, primary key
#  desired_employment :string
#  desired_location   :string
#  desired_salary     :string
#  dob                :date
#  experience         :string
#  facebook_link      :string
#  gender             :string
#  github_link        :string
#  hometown           :string
#  key_skills         :string
#  language_known     :string
#  linkedin_link      :string
#  marital_status     :string
#  permanent_address  :string
#  phone_no           :string
#  pincode            :string
#  state              :string
#  summary            :string
#  twitter_link       :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#  user_id            :bigint
#
# Indexes
#
#  index_profiles_on_user_id  (user_id)
#
class Profile < ApplicationRecord
    belongs_to :user
    has_rich_text :summary
    has_one_attached :avatar
    has_one_attached :resume
    has_many :work_experience
    accepts_nested_attributes_for :work_experience, allow_destroy: true, reject_if: :all_blank
  

    GENDER = [
        "Male",
        "Female",
        "Transgender"
    ].freeze

    MARITAL_STATUS = [
        "Single/Unmarried",
        "Married",
        "Widowed",
        "Divorced",
        "Seperated",
        "Other"
    ].freeze

    DESIRED_EMPLOYMENT = [
        "Contract",
        "Full-time"
      ]
      
    DESIRED_SALARY = [
    "30,000 - 35,000",
    "35,000 - 40,000",
    "40,000 - 50,000",
    "50,000 - 60,000",
    "60,000 - 70,000",
    "70,000 - 80,000",
    "80,000 - 90,000",
    "80,000 - 100,000",
    "100,000 - 120,000",
    "120,000 - 130,000",
    "130,000 - 140,000",
    "140,000 - 150,000",
    "150,000 - 160,000",
    "160,000 - 170,000",
    "170,000 - 180,000",
    "180,000 - 190,000",
    "190,000 - 200,000",
    "200,000 - 210,000",
    "210,000 - 220,000",
    "Greater then 220,000"
    ]
    YEARS_OF_EXPERIENCE_RANGE = ["1", "2", "3", "4", "5", "6", "7", "8","9", "more than 10"]
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: %i[ show edit update destroy ]

  # GET /profiles or /profiles.json
  def index
    @jobs = current_user.jobs.desc
    
  end

  # GET /profiles/1 or /profiles/1.json
  def show
  end

  # GET /profiles/new
  def new
    @profile = Profile.new
  end

  # GET /profiles/1/edit
  def edit
  end

  # POST /profiles or /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id
    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: "Profile was successfully created." }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new, status: :unprocessable_entity , notice: @profile.errors.full_messages}
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1 or /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: "Profile was successfully updated." }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1 or /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: "Profile was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:summary,:avatar,:resume, :key_skills, :experience, :desired_location, :desired_employment, :desired_salary, :language_known, :facebook_link, :twitter_link, :linkedin_link, :github_link, :gender, :phone_no, :marital_status, :dob, :hometown, :state, :pincode, :permanent_address,work_experience_attributes: [:id, :company_name, :job_position, :date_from, :date_to, :location, :description, :_destroy])
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_developer.html.erb
<!--
<% if current_user.profile.present? %>
<div class="row">
  <div class="col-md-12 mx-auto">
    <div class="bg-white shadow rounded overflow-hidden">
      <div class="px-4 pt-0 pb-4 cover">
        <div class="media align-items-end profile-head">
          <div class="profile mr-3">
            <%  if current_user.profile.avatar.present? %>
              <%= image_tag current_user.profile.avatar,  class:"rounded mb-2 img-thumbnail", style: "width: 200px;" %>
            <% else %>
              <%= image_tag "user-img", class:"rounded mb-2 img-thumbnail" %>
            <% end %>
          </div>
          <div class="media-body mb-5 text-white">
            <h2 class="mt-0 mb-0"><%= current_user.profile.user.name %></h2>
            <p class="small mb-0"><%= current_user.profile.user.email %></p>
            <p class="small mb-0"><%= current_user.profile.gender %> &bull; <%= current_user.profile.marital_status%></p>
            <p class="small mb-0"><%= current_user.profile.phone_no %></p>
            <p class="small mb-2"><i class="fas fa-map-marker-alt mr-2"></i><%= current_user.profile.hometown %> , <%= current_user.profile.state%></p>
            <p class="small mb-4">
              <a href="<%= current_user.profile.facebook_link%>"><i class="fab fa-facebook mr-2 text-white"></i></a>
              <a href="<%= current_user.profile.twitter_link%>"><i class="fab fa-twitter mr-2 text-white"></i></a>
              <a href="<%= current_user.profile.linkedin_link%>"><i class="fab fa-linkedin mr-2 text-white"></i></a>
              <a href="<%= current_user.profile.github_link%>"><i class="fab fa-github mr-2 text-white"></i></a>
            </p>
          </div>
        </div>
      </div>
      <div class="bg-light p-4 d-flex justify-content-end text-center">
        <div>
        
				</div>
        <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <h5 class="font-weight-bold mb-0 d-block">215</h5><small class="text-muted"> <i class="fas fa-image mr-1"></i>Photos</small>
          </li>
          <li class="list-inline-item">
            <h5 class="font-weight-bold mb-0 d-block">745</h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Followers</small>
          </li>
          <li class="list-inline-item">
            <h5 class="font-weight-bold mb-0 d-block">340</h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Following</small>
          </li>
        </ul>
      </div>
      <h3 class="ml-4"> User Information</h3>
      <div class="px-4 py-3">
        <h4 class="mb-0">About</h4>
        <div class="p-2 rounded shadow-sm bg-light">
          <p class=" mb-0"><%= current_user.profile.summary%></p>
        </div>
      </div>
      <div class="px-4 py-3">
        <div class="row">
          <div class="col-lg-6 ">
            <h4 class="mb-0">Key Skills</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= current_user.profile.key_skills%></p>
            </div>                                           
          </div>
          <div class="col-lg-6">
            <h4 class="mb-0">language known</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class="mb-0"><%= current_user.profile.language_known%></p>
            </div>  
          </div>
        </div> 
      </div>
      <div class="px-4 py-3">
        <div class="row">
          <div class="col-sm-3">
            <h4 class="mb-0">Desired Location</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= current_user.profile.desired_location %></p>
            </div>
          </div>
          <div class="col-sm-3">
            <h4 class="mb-0">Desired Employment</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= current_user.profile.desired_employment %></p>
            </div>
          </div>
          <div class="col-sm-3">
            <h4 class="mb-0">Desired Salary</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= current_user.profile.desired_salary %></p>
            </div>
          </div>
          <div class="col-sm-3">
            <h4 class="mb-0">Experience</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class="mb-0"><%= current_user.profile.experience%></p>
            </div>
          </div>
        </div>
      </div><hr>
      <h3 class="ml-4">Work Experience</h3>
      <%  current_user.profile&.work_experience.each do |work| %>
        <div class="px-4">
         #<%= cycle("1","2","3","4")%>
        </div>
        <div class="px-4 py-3">
          <div class="row">
            <div class="col-sm-6">
              <h4 class="mb-0">company_name</h4>
              <div class="p-2 rounded shadow-sm bg-light">
                  <p class=" mb-0"><%= work.company_name%></p>
              </div>
            </div>
            <div class="col-sm-6">
              <h4 class="mb-0">Job Position</h4>
              <div class="p-2 rounded shadow-sm bg-light">
                  <p class=" mb-0"><%= work.job_position %></p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-4">
              <h4 class="mb-0">Location</h4>
              <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= work.location %></p>
              </div>
            </div>
            <div class="col-sm-4">
              <h4 class="mb-0">From</h4>
              <div class="p-2 rounded shadow-sm bg-light">
                  <p class=" mb-0"><%= work.date_from %></p>
              </div>
            </div>
            <div class="col-sm-4">
              <h4 class="mb-0">To</h4>
              <div class="p-2 rounded shadow-sm bg-light">
                  <p class="mb-0"><%= work.date_to %></p>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-12">
              <h4 class="mb-0">Description</h4>
              <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= work.description %></p>
              </div>
            </div>
          </div>
        </div>
      <% end %><hr>
      <h3 class="ml-4"> Contact Information</h3>
      <div class="px-4 py-3">
        <h4 class="mb-0">Address</h4>
        <div class="p-2 rounded shadow-sm bg-light">
          <p class=" mb-0"><%= current_user.profile.permanent_address%></p>
        </div>
      </div>
      <div class="px-4 py-3">
        <div class="row">
          <div class="col-lg-6">
            <h4 class="mb-0">Phone No</h4>
            <div class="p-2 rounded shadow-sm bg-light">
              <p class=" mb-0"><%= current_user.profile.phone_no%></p>
            </div>
          </div>
          <div class="col-lg-6">
            <h4 class="mb-0">Email Address</h4>
            <div class="p-2 rounded shadow-sm bg-light">
              <p class=" mb-0"><%= current_user.profile.user.email%></p>
            </div>
          </div>
        </div>
      </div>
      <div class="px-4 py-3">
        <div class="row">
          <div class="col-lg-4">
            <h4 class="mb-0">Hometown</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= current_user.profile.hometown%></p>
            </div>                                      
          </div>
          <div class="col-lg-4">
            <h4 class="mb-0">State</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= current_user.profile.state%></p>
            </div>                                      
          </div>
          <div class="col-lg-4">
            <h4 class="mb-0">pincode</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= current_user.profile.pincode%></p>
            </div>
          </div>
        </div>
      </div>
            <%# <div class="py-4 px-4">
                <div class="d-flex align-items-center justify-content-between mb-3">
                    <h5 class="mb-0">Recent photos</h5><a href="#" class="btn btn-link text-muted">Show all</a>
                </div>
                <div class="row">
                    <div class="col-lg-6 mb-2 pr-lg-1"><img src="https://images.unsplash.com/photo-1469594292607-7bd90f8d3ba4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm"></div>
                    <div class="col-lg-6 mb-2 pl-lg-1"><img src="https://images.unsplash.com/photo-1493571716545-b559a19edd14?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm"></div>
                    <div class="col-lg-6 pr-lg-1 mb-2"><img src="https://images.unsplash.com/photo-1453791052107-5c843da62d97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="" class="img-fluid rounded shadow-sm"></div>
                    <div class="col-lg-6 pl-lg-1"><img src="https://images.unsplash.com/photo-1475724017904-b712052c192a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm"></div>
                </div>
            </div> %>
    </div>
  </div>

     
        <% else %>
          Create your profile so that other can see you profile
          <%= link_to "Profile", new_profile_path, class: "btn btn-primary"%>
          <%= link_to 'Edit Account', edit_user_registration_path, class: "btn btn-default" %>
        <% end %>  

-->

app/views/profiles/_work_experience_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-lg-6">
      <%= f.hidden_field :_destroy %>
      <div class="form-group focused">
        <%= f.label :company_name %>
        <%= f.text_field :company_name,class: "form-control"  %>	
			</div>
		</div>
		<div class="col-lg-6">
			<div class="form-group">
				<%= f.label :job_position %>
        <%= f.text_field :job_position,class: "form-control"  %>
			</div>
		</div>
  </div>
  <div class="row">
		<div class="col-lg-4">
			<div class="form-group ">
			  <%= f.label :location %>
        <%= f.text_field :location ,class: "form-control" %>
			</div>
		</div>
		<div class="col-lg-4">
			<div class="form-group">
				<%= f.label :date_from %>
        <%= f.date_field :date_from ,class: "form-control" %>
			</div>
		</div>
		<div class="col-lg-4">
			<div class="form-group">
			  <%= f.label :date_to %>
        <%= f.date_field :date_to,class: "form-control"  %>
			</div>
		</div>
	</div>
	<div class="row">
	  <div class="col-12">
		  <%= f.label :description %>
      <%= f.text_field :description,class: "form-control"  %>
		</div>
  </div>
  <%= link_to "Remove", '#', class: "remove_fields" %>
</div>
   

app/views/profiles/show.html.erb
<div class="row py-5 px-4">
  <div class="col-md-12 mx-auto">
    <!-- Profile widget -->
    <div class="bg-white shadow rounded overflow-hidden">
      <div class="px-4 pt-0 pb-4 cover">
        <div class="media align-items-end profile-head">
          <div class="profile mr-3">
            <%  if @profile.avatar.present? %>
              <%= image_tag @profile.avatar,  class:"rounded mb-2 img-thumbnail", style: "width: 200px;" %>
            <% else %>
              <%= image_tag "user-img", class:"rounded mb-2 img-thumbnail" %>
            <% end %>
          </div>
          <div class="media-body mb-5 text-white">
            <h2 class="mt-0 mb-0"><%= @profile.user.name %></h2>
            <p class="small mb-0"><%= @profile.user.email %></p>
            <p class="small mb-0"><%= @profile.gender %> &bull; <%= @profile.marital_status%></p>
            <p class="small mb-0"><%= @profile.phone_no %></p>
            <p class="small mb-2"><i class="fas fa-map-marker-alt mr-2"></i><%= @profile.hometown %> , <%= @profile.state%></p>
            <p class="small mb-4">
              <a href="<%= @profile.facebook_link%>"><i class="fab fa-facebook mr-2 text-white"></i></a>
              <a href="<%= @profile.twitter_link%>"><i class="fab fa-twitter mr-2 text-white"></i></a>
              <a href="<%= @profile.linkedin_link%>"><i class="fab fa-linkedin mr-2 text-white"></i></a>
              <a href="<%= @profile.github_link%>"><i class="fab fa-github mr-2 text-white"></i></a>
            </p>
          </div>
        </div>
      </div>
      <div class="bg-light p-4 d-flex justify-content-end text-center">
        <div>
          <% if user_signed_in? && current_user.id == @profile.user.id || admin?%>
            <%= link_to 'Edit Profile', edit_profile_path(@profile) , class: "btn btn-primary btn-sm" %>
            <%= link_to 'Edit Account', edit_user_registration_path, class: "btn btn-default btn-sm" %>
          <% end %>
          <a href="#" class="btn btn-info btn-sm">Connect</a>
          <%= link_to "Message", conversations_path(sender_id: current_user.id, recipient_id: @profile.user.id), method: :post , class:"btn btn-default btn-sm"%>
        </div>
        <ul class="list-inline mb-0">
          <li class="list-inline-item">
            <h5 class="font-weight-bold mb-0 d-block">215</h5><small class="text-muted"> <i class="fas fa-image mr-1"></i>Photos</small>
          </li>
          <li class="list-inline-item">
            <h5 class="font-weight-bold mb-0 d-block">745</h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Followers</small>
          </li>
          <li class="list-inline-item">
            <h5 class="font-weight-bold mb-0 d-block">340</h5><small class="text-muted"> <i class="fas fa-user mr-1"></i>Following</small>
          </li>
        </ul>
      </div>
      <div class="px-4 py-3">
        <h4 class="mb-0">About</h4>
        <div class="p-2 rounded shadow-sm bg-light">
          <p class=" mb-0"><%= @profile.summary%></p>
        </div>
      </div>
        <div class="px-4 py-3">
        <div class="row">
          <div class="col-lg-6 ">
            <h4 class="mb-0">Key Skills</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= @profile.key_skills%></p>
            </div>                                           
          </div>
          <div class="col-lg-6">
            <h4 class="mb-0">language known</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class="mb-0"><%= @profile.language_known%></p>
            </div>  
          </div>
        </div>
          
      </div>
      <div class="px-4 py-3">
        <div class="row">
          <div class="col-3">
            <h4 class="mb-0">Desired Location</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= @profile.desired_location %></p>
            </div>
          </div>
          <div class="col-3">
            <h4 class="mb-0">Desired Employment</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= @profile.desired_employment %></p>
            </div>
          </div>
          <div class="col-3">
            <h4 class="mb-0">Desired Salary</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= @profile.desired_salary %></p>
            </div>
          </div>
          <div class="col-3">
            <h4 class="mb-0">Experience</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class="mb-0"><%= @profile.experience%></p>
            </div>
          </div>
        </div>
      </div>
      
      <div class="px-4 py-3">
        <h4 class="mb-0">Address</h4>
        <div class="p-2 rounded shadow-sm bg-light">
            <p class=" mb-0"><%= @profile.permanent_address%></p>
        </div>
      </div>
      <div class="px-4 py-3">
        <div class="row">
          <div class="col-lg-4">
            <h4 class="mb-0">Hometown</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= @profile.hometown%></p>
            </div>                                      
          </div>
          <div class="col-lg-4">
            <h4 class="mb-0">State</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= @profile.state%></p>
            </div>                                      
          </div>
          <div class="col-lg-4">
            <h4 class="mb-0">pincode</h4>
            <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= @profile.pincode%></p>
            </div>
          </div>
        </div>
      </div>
            <%# <div class="py-4 px-4">
                <div class="d-flex align-items-center justify-content-between mb-3">
                    <h5 class="mb-0">Recent photos</h5><a href="#" class="btn btn-link text-muted">Show all</a>
                </div>
                <div class="row">
                    <div class="col-lg-6 mb-2 pr-lg-1"><img src="https://images.unsplash.com/photo-1469594292607-7bd90f8d3ba4?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm"></div>
                    <div class="col-lg-6 mb-2 pl-lg-1"><img src="https://images.unsplash.com/photo-1493571716545-b559a19edd14?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm"></div>
                    <div class="col-lg-6 pr-lg-1 mb-2"><img src="https://images.unsplash.com/photo-1453791052107-5c843da62d97?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1350&q=80" alt="" class="img-fluid rounded shadow-sm"></div>
                    <div class="col-lg-6 pl-lg-1"><img src="https://images.unsplash.com/photo-1475724017904-b712052c192a?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=750&q=80" alt="" class="img-fluid rounded shadow-sm"></div>
                </div>
            </div> %>
    </div>
  </div>
</div><div class="row mt-5">
  <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
    <div class="card card-profile shadow">
      <div class="row justify-content-center">
        <div class="col-lg-3 order-lg-2">
          <div class="card-profile-image mt-5">
            <%  if @profile.avatar.present? %>
              <%= image_tag @profile.avatar, class: "rounded-circle  z-depth-2", style: "background-size: cover;"%>
            <% else %>
              <%= image_tag "user-img", class: "rounded-circle"%>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
        <div class="d-flex justify-content-between">
          <a href="#" class="btn btn-sm btn-info mr-4">Connect</a>
          <a href="#" class="btn btn-sm btn-default float-right">Message</a>
        </div>
      </div>
      <div class="card-body pt-0 pt-md-4">
        <div class="text-center">
          <% age = @profile.dob.year - Date.today.year %>
          <h3><%= @profile.user.name %> <span class="font-weight-light"> <%=  age %> </span></h3>
          <div class="h5 font-weight-300">
            <%= @profile.hometown %>
          </div>
          <div class="h5 mt-4">
            <%= @profile.gender%> &bull;
            <%= @profile.marital_status%><br>
            <%= @profile.dob%>
          </div>
          <div>University of Computer Science</div>
          <%# <hr class="my-4">
          <p>Ryan — the name taken by Melbourne-raised, Brooklyn-based Nick Murphy — writes, performs and records all of his own music.</p>
          <a href="#">Show more</a> %>
        </div>
        <div class="row">
          <div class="col">
            <div class="card-profile-stats d-flex justify-content-center mt-md-5">
              <div>
                <span class="heading">22</span>
                <span class="description">Friends</span>
              </div>
              <div>
                <span class="heading">10</span>
                <span class="description">Photos</span>
              </div>
              <div>
                <span class="heading">89</span>
                <span class="description">Comments</span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-xl-8 order-xl-1">
    <div class="card bg-secondary shadow">
      <div class="card-header bg-white border-0">
        <div class="row align-items-center">
          <div class="col-6">
            <h3 class="mb-0">User Details</h3>
          </div>
          <div class="col-6 text-right">
            <% if user_signed_in? && current_user.id == @profile.user.id || admin?%>
              <%= link_to 'Edit Profile', edit_profile_path(@profile) , class: "btn btn-primary" %>
              <%= link_to 'Edit Account', edit_user_registration_path, class: "btn btn-default" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="card-body">
        <h6 class="heading-small text-muted mb-4">ABOUT ME</h6>
        <div class="pl-lg-4">
          <div  class="mb-3">
            <label>Summary</label>
            <p class="text-muted"><%= @profile.summary%></p>
          </div>
          <div class="mb-3">
            <p>Key skills</p>
            <%= @profile.key_skills%>
          </div>
          <div class="row">
            <div class="col-lg-4">
              <p>Desired Location</p>
              <%= @profile.desired_location%>
            </div>
            <div class="col-lg-4">
              <p>Desired Employment</p>
              <%= @profile.desired_employment%>                                         
            </div>
            <div class="col-lg-4">
              <p>Desired Salary</p>
              <%= @profile.desired_salary%>                                               
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6 ">
              <p>Language Known</p>
              <%= @profile.language_known%>                                         
            </div>
            <div class="col-lg-6">
              <p>Experience</p>
              <%= @profile.experience%>
            </div>
          </div>
        </div>                
        <hr class="my-4">
        <!-- Address -->
        <h6 class="heading-small text-muted mb-4">Contact information</h6>
        <div class="pl-lg-4">
          <div class="row">
            <div class="col-md-12">
              <div class="form-group focused">
                <p>Address</p>
                <%= @profile.permanent_address%>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-6">
                <p>Hometown</p>
                <%= @profile.hometown%>
            </div>
            <div class="col-lg-6">
                <p>Pincode</p>
                <%= @profile.pincode%>
            </div>
          </div>
        </div>
        <%# <hr class="my-4">
        <!-- Description -->
        <h6 class="heading-small text-muted mb-4">Contact Inormation</h6>
        <div class="pl-lg-4">
          <div class="form-group focused">
            <label>About Me</label>
            <textarea rows="4" class="form-control form-control-alternative" placeholder="A few words about you ...">A beautiful Dashboard for Bootstrap 4. It is Free and Open Source.</textarea>
          </div>
        </div> %>
      </div>
    </div>
  </div>
</div>