config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :jobs
  root 'home#index'
  devise_for :users
  resources :conversations do
    resources :messages
   end
  get '/developers', to: "home#developers"
  mount SimpleDiscussion::Engine => "/forum"
  put 'jobs/:id/publish', to: "jobs#publish", as: "publish"
  put 'jobs/:id/unpublish', to: "jobs#unpublish", as: "unpublish"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/job.rb
# == Schema Information
#
# Table name: jobs
#
#  id                  :bigint           not null, primary key
#  company_name        :string
#  company_website     :string
#  compensation_range  :string
#  compensation_type   :string
#  deleted_at          :datetime
#  estimated_hours     :string
#  featured            :boolean          default(FALSE)
#  headquarters        :string
#  link_to_apply       :string
#  price               :integer
#  published_at        :datetime
#  remote              :boolean          default(FALSE)
#  role_type           :string
#  slug                :string
#  status              :string           default("pending")
#  title               :string
#  upsell_type         :string
#  years_of_experience :string
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#  user_id             :bigint           not null
#
# Indexes
#
#  index_jobs_on_deleted_at  (deleted_at)
#  index_jobs_on_slug        (slug) UNIQUE
#  index_jobs_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Job < ApplicationRecord
  acts_as_paranoid
  extend FriendlyId
  friendly_id :title, use: :slugged

  # relations
  belongs_to :user
  has_rich_text :description
  has_rich_text :company_description
  has_one_attached :company_logo
  validates :title,:description,:company_name,:company_description,:link_to_apply, presence: true
   
  
  #scopes
  scope :desc, -> { order(published_at: :desc)}
  scope :pending, -> { where(status: JOB_STATUSES[:pending]) }
  scope :published, -> { where(status: JOB_STATUSES[:published]) }
  scope :archived, -> { where(status: JOB_STATUSES[:archived]) }



  # contants
  COMPENSATION_TYPE = [
    "Contract",
    "Freelance",
    "Part-time",
    "Full-time"
  ]
  
  COMPENSATION_RANGE = [
    "30,000 - 35,000",
    "35,000 - 40,000",
    "40,000 - 50,000",
    "50,000 - 60,000",
    "60,000 - 70,000",
    "70,000 - 80,000",
    "80,000 - 90,000",
    "80,000 - 100,000",
    "100,000 - 120,000",
    "120,000 - 130,000",
    "130,000 - 140,000",
    "140,000 - 150,000",
    "150,000 - 160,000",
    "160,000 - 170,000",
    "170,000 - 180,000",
    "180,000 - 190,000",
    "190,000 - 200,000",
    "200,000 - 210,000",
    "210,000 - 220,000",
    "Greater then 220,000"
  ]

  JOB_STATUSES = {
    pending: "pending",
    published: "published",
    archived: "archived"
  }.freeze

  HOURLY_RANGE = [
    "less then 10",
    "10-30",
    "30-60",
    "60-90",
    "more than 100",
  ].freeze
  
  YEARS_OF_EXPERIENCE_RANGE = ["1", "2", "3", "4", "5", "6", "7", "8","9", "more than 10"]
  
  def pending?
    self.status == Job::JOB_STATUSES[:pending]
  end

  def published?
    self.status == Job::JOB_STATUSES[:published]
  end
  
  def archived?
    self.status == Job::JOB_STATUSES[:archived]
  end
  
  def badge_color
    case status
    when 'pending'
      'secondary'
    when 'archive'
      'info'
    when 'published'
      'success'
    end
  end
  def should_generate_new_friendly_id?
    if !slug?
      title_changed?
    else
      false
    end
  end
  
  def self.search(search)
    if search 
      search.downcase!
      where(["slug LIKE ? OR LOWER(company_name) LIKE ? ","%#{search}%","%#{search}%"])
    end
  end 
  
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]

  # GET /jobs or /jobs.json
  def index
    @jobs = current_user.jobs.desc
  end

  # GET /jobs/1 or /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = current_user.jobs.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs or /jobs.json
  def create
    @job = current_user.jobs.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: "Job was successfully created." }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1 or /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: "Job was successfully updated." }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1 or /jobs/1.json
  def destroy
    @job.update status: "archived"
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: "Job was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def publish
    job = current_user.jobs.friendly.find(params[:id])
    job.update(status: "published",published_at: Time.now)
    flash[:notice] = "published Succesfully"
    redirect_to request.referrer  
    # redirect_to job
  end

  def unpublish
    job = current_user.jobs.friendly.find(params[:id])
    job.update(status: "pending")
    flash[:notice] = "Status changed form published to pending"
    redirect_to request.referrer  
  end
 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_params
      params.require(:job).permit(:company_name, :company_website, :company_logo, :description, :company_description, :compensation_range, :compensation_type, 
        :estimated_hours, :headquarters, :link_to_apply, :price, :remote, 
        :title, :upsell_type, :years_of_experience,)
    end

    
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.erb
<%= simple_form_for(job) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
        <% job.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="card mb-5 border border-dark bg-secondary shadow">
    <div class= "card-body m-4">
        <%= form.input :title ,placeholder: "Title"%>
        <%= form.input :link_to_apply, as: :url%>
        <%= form.input :description,as: :rich_text_area  %>
        <div class="row">
          <div class="col-sm-3">
            <%= form.label :compensation_type %>
            <%= form.select :compensation_type, options_for_select(Job::COMPENSATION_TYPE),  { :include_blank=>false },class: "form-control" %>
          </div>
          <div class="col-sm-3">
            <%= form.label :compensation_range %>
            <%= form.select :compensation_range, options_for_select(Job::COMPENSATION_RANGE), { :include_blank=>false }, { :class => 'form-control' } %>
          </div>
          <div class="col-sm-2">
            <%= form.label :estimated_hours%>
            <%= form.select :estimated_hours, options_for_select(Job::HOURLY_RANGE),  { :include_blank=>false },{:class => 'form-control' } %>
          </div>
          <div class="col-sm-3">
            <%= form.label :years_of_experience %>
            <%= form.select :years_of_experience, options_for_select(Job::YEARS_OF_EXPERIENCE_RANGE), { :include_blank=>false }, class: "form-control"%>
          </div>
          <div class="col-sm-1">
            <%# <div class="custom-control custom-checkbox"> %>
              <%= form.check_box :remote, class:"custom-control-input",id:"materialChecked" %>
              <%= form.label "Remote" ,class:"custom-control-label", for:"materialChecked"%>
            <%# </div> %>
          </div>
        </div>
        
        <div class="row">
        <div class="col-sm-8">
          <%= form.input :company_name %>
          <%= form.label :company_logo%>
          <%= form.file_field :company_logo , class: "form-control-file" %>
        </div>
        <div class="col-sm-4">
          <div class="row">
            <div class="col-6">
            </div>
            <div class="col-6">
              <% if form.object.company_logo.attached?%>
              <%= image_tag form.object.company_logo.variant(resize_to_fit: [200, 200]), class: "img-fluid rounded img-thumbnail" %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-6">
          <%= form.input :headquarters %>
        </div>
        <div class="col-sm-6">
          <%= form.input :company_website %>
        </div>
      </div>
      <%= form.input:company_description ,as: :rich_text_area%>

          <label class="continue">
            <%= form.submit "Save", class: "btn btn-success btn-lg"%>
          </label>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<div class="rounded mt-5">
  <div class="row">
    <div class="col-lg-2 mb-4 mb-lg-0">
      <!-- Vertical Menu-->
        <%= render "shared/verticle_menu"%>
      <!-- End -->
    </div>
    <div class="col-lg-10 mb-5">
      <div class="d-flex justify-content-between mt-4 mb-4">
        <%= link_to 'Show', @job, class:  "btn btn-secondary" %> 
        <h3 class="text-center"> Edit your job <%= @job.title %></h3>
        <%= link_to 'Back', jobs_path, class: "btn btn-info" %>
      </div>
      <%= render 'form', job: @job %>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="rounded mt-5">
  <div class="row">
    <div class="col-lg-2 mb-4 mb-lg-0">
      <!-- Vertical Menu-->
        <%= render "shared/verticle_menu"%>
      <!-- End -->
    </div>
      <div class="col-lg-10 mb-5">
        <div class="d-flex justify-content-between">
          <h3>Your Job listing</h3>
          <%= link_to 'New Job', new_job_path, class: "btn btn-primary" %>    
        </div>
<div class="row" , style="justify-content: center">
  <% @jobs.each do |job| %>
    <div class="card job-index col-md-3 mt-5 ">
      <%= link_to job , class: "text-decoration-none" do %>
        <div class="card-content">
          <div class="card-body p-0">
            <div class="profile d-flex justify-content-between">
              <div>
                <% if job.company_logo.attached?%>
                  <%= image_tag job.company_logo %>
                <% else %>
                  <%= image_tag "company-img" %>
                <% end %>
              </div>
              <div>
                <span class="badge badge-<%= job.badge_color%>"><%= job.status%></span>
              </div>
            </div>
            
            <div class="card-title mt-3"><%= job.title %><br /> <small><%= job.company_name %></small> </div>
              <div class="card-subtitle">
                <p> <small class="text-muted">
                  <%= truncate(strip_tags(job.description.to_s), length: 50)%><br>
                  <%= job.compensation_type %> <br>
                  <%= job.compensation_range %><br>
                  <%= job.years_of_experience %> years of experience<br>
                  </small> 
                </p>
              </div>
                <%= link_to 'Edit', edit_job_path(job) , class: "btn btn-info btn-sm"%>        
                <% if job.published? %>
                  <%= link_to 'Unpublish', unpublish_path(job), method: :put , class: "btn btn-warning btn-sm"%>        
                <% else %>
                  <%= link_to 'publish', publish_path(job), method: :put , class: "btn btn-success btn-sm"%>        
                <% end %>
                <%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
                <small class="text-muted">Published at: <%= time_ago_in_words(job.published_at) if job.published? %> ago</small>
            </div>
          </div>
      <% end %>
    </div>
  <% end %>
</div>
</div>
</div>
</div>

app/views/jobs/new.html.erb
<div class="rounded mt-5">
  <div class="row">
    <div class="col-lg-2 mb-4 mb-lg-0">
      <!-- Vertical Menu-->
        <%= render "shared/verticle_menu"%>
      <!-- End -->
    </div>
    <div class="col-lg-10 mb-5">
      <div class="d-flex justify-content-between mt-4 mb-4">
        <h3>New Job</h3>
        <%= link_to 'Back', jobs_path , class: "btn btn-info"%>
      </div>
      <%= render 'form', job: @job %>
    </div>
  <div>
<div>

app/views/jobs/show.html.erb
<div class="mt-5">
  <div class="d-flex justify-content-between mb-3">
    <%= link_to 'Back to all jobs', root_path, class: "btn btn-default" %>
    <% if author_of(@job) || admin?%>
    <%= link_to 'Edit', edit_job_path(@job), class: "btn btn-warning" %>
    <% end %>
  </div>
    <div class="row">
      <div class="col-xl-4 order-xl-2 mb-5 mb-xl-0">
        <div class="card card-profile shadow">
          <div class="row justify-content-center">
            <div class="col-lg-3 order-lg-2">
              <div class="card-profile-image mt-5">
                <% if @job.company_logo.attached?%>
                  <%= image_tag @job.company_logo, class: "rounded-circle" %>
                <% else %>
                  <%= image_tag "company-img", class: "rounded-circle" %>
                <% end %>
              </div>
            </div>
          </div>
          <div class="card-header text-center border-0 pt-8 pt-md-4 pb-0 pb-md-4">
            <div class="d-flex justify-content-between">
              <a href="#" class="btn btn-sm btn-info mr-4">Connect</a>
              <a href="#" class="btn btn-sm btn-default float-right">Message</a>
            </div>
          </div>
          <div class="card-body pt-0 pt-md-4">
            <div class="text-center">
              <h3>
                <%= @job.company_name %><span class="font-weight-light"></span>
              </h3>
              <div class="h5 font-weight-300">
                <i class="ni location_pin mr-2"></i><%= @job.headquarters %>
              </div>
              <div class="h5">
                <i class="ni business_briefcase-24 mr-2"></i><%= @job.company_description %>
              </div>
              <div>
                <i class="ni education_hat mr-2"></i><%= @job.company_website %>
              </div>
                <%= link_to "Apply for this role", @job.link_to_apply, class: "btn btn-primary"%>
              <%# <hr class="my-4">
              <p>Ryan — the name taken by Melbourne-raised, Brooklyn-based Nick Murphy — writes, performs and records all of his own music.</p>
              <a href="#">Show more</a> %>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xl-8 order-xl-1">
        <div class="card bg-white shadow rounded overflow-hidden">
          <div class="card-header bg-light border-0">
            <div class="row align-items-center">
              <div class="col-8">
                <h3 class="mb-0"><%= @job.title %></h3>
              </div>
              <div class="col-4 text-right">
                <a href="#!" class="btn btn-sm btn-primary">Settings</a>
              </div>
            </div>
          </div>
          <div class="card-body">
            <div class="px-4 py-3">
              <h4 class="mb-0">About the role</h4>
              <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= @job.description %></p>
              </div>
            </div>
           
            <div class="px-4 py-3">
              <h4 class="mb-0">COMPENSATION TYPE</h4>
              <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= @job.compensation_type %> </p>
              </div>
            </div>
            
            <div class="px-4 py-3">
              <h4 class="mb-0">COMPENSATION RANGE</h4>
              <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= number_to_currency(@job.compensation_range) %></p>
              </div>
            </div>
            
            <div class="px-4 py-3">
              <h4 class="mb-0">EXPERIENCE</h4>
              <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= pluralize(@job.years_of_experience, "year") %> of experience</p>
              </div>
            </div>
           
            <div class="px-4 py-3">
              <h4 class="mb-0">HOURLY RANGE</h4>
              <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"><%= @job.estimated_hours %></p>
              </div>
            </div>
            
            <div class="px-4 py-3">
              <h4 class="mb-0">REMOTE</h4>
              <div class="p-2 rounded shadow-sm bg-light">
                <p class=" mb-0"> <%= @job.remote %></p>
              </div>
            </div>
            
          </div>
        </div>
      </div>
  </div>
</div>