config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :jobs
  root 'home#index'
  devise_for :users
  resources :conversations do
    resources :messages
   end
  get '/developers', to: "home#developers"
  mount SimpleDiscussion::Engine => "/forum"
  put 'jobs/:id/publish', to: "jobs#publish", as: "publish"
  put 'jobs/:id/unpublish', to: "jobs#unpublish", as: "unpublish"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<footer class="footer">
  <div class="row align-items-center justify-content-xl-between">
    <div class="col-xl-6 m-auto text-center">
      <div class="copyright">
        <p>Made with <a href="https://www.creative-tim.com/product/argon-dashboard" target="_blank">Argon Dashboard</a> by Creative Tim</p>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-custom navbar-expand-lg navbar-dark navbar-fixed-top" id="navbar_top">
  <div class="container">
    <img src="https://img.icons8.com/color/48/000000/ruby-programming-language.png"  alt="" class="img-fluid mb-3 d-md-block"/>
  <%= link_to "RailsDeveloper", root_path, class: "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item <%= current_page?(root_path) ? "active" : ""  %>">
        <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <% if !user_signed_in? %>
        <% if current_page?(new_user_session_path) %>
          <li class="nav-item">
            <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      <% end %>
      <% if user_signed_in? %>
      <i class="fas fa-bell"></i>
        <li class="nav-item dropdown">
          <span class="avatar avatar-sm rounded-circle">
          <%  if current_user&.profile&.avatar&.attached? %>
            <%= image_tag current_user.profile.avatar, class: "rounded-circle"%>
          <% else %>
            <%= image_tag "user-img", class: "rounded-circle"%>
          <% end %>
          </span>
        </li>
        <li class="nav-item <%= current_page?(jobs_path) ? "active" : ""  %>">
            <%= link_to current_user.name, profiles_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "nav-link btn btn-danger btn-sm" %>
        </li>
      <% end %>
    </ul>
  </div>

  </div>

</nav> 
<%  if current_page?(root_path) %>
  <div class="header pb-8 pt-5 pt-lg-8 d-flex align-items-center" style="min-height: 200px; ">
    <!-- Mask -->
    <span class="mask bg-gradient-default"></span>
    <!-- Header container-->
    <div class="container-fluid align-items-center">
      <div class="row">
        <div class="col">
          <h1 class="display-2 text-white">Find Ruby On Rails Developer</h1>
          <p class="text-white mt-0">The internet's number one source for Ruby On Rails Developer </p>
            <%# <img src="https://img.icons8.com/plasticine/100/000000/find-matching-job.png"/> %>
            <%= link_to "Find a developer", developers_path, class: "btn btn-primary"%>
            <%= link_to "Find a job", root_path(anchor: "card-profile"), class: "btn btn-outline-info" %>
          <p class="text-white mt-2"> or Find a Job of your wish</p>
        </div>
      </div>
    </div> 
  </div> 
<% end %>

app/views/shared/_notices.html.erb
<% flash.each do |msg_type, message| %>
  <div class="alert <%= bootstrap_class_for(msg_type) %> mt-3">
    <div class="container">
      <button class="close" data-dismiss="alert"><span>×</span></button>
      <%= message %>
    </div>
  </div>
<% end %>

app/views/shared/_spacer.html.erb
<hr/>

app/views/shared/_verticle_menu.html.erb
 <nav class="nav flex-column bg-white shadow-sm rounded p-2">
  <%= link_to profiles_path, class:"nav-link px-4 rounded-pill" do %>
      <i class="fas fa-chart-line"></i>
      Dashboard
  <% end %>
  <%= link_to conversations_path, class:"nav-link px-4 rounded-pill" do %>
      <i class="fas fa-envelope"></i>
      Messages
      <span class="badge badge-primary  rounded-pill ml-2">17</span>
  <% end %>
  <% if current_user.employer %>
    <%= link_to jobs_path, class:"nav-link px-4 rounded-pill" do %>
      <i class="fas fa-line-chart mr-2"></i>
      Jobs
      <span class="badge badge-primary px-2 rounded-pill ml-2"><%= current_user.jobs.count%></span>
    <% end %>
     <%= link_to new_job_path, class:"nav-link px-4 rounded-pill" do %>
      <i class="fas fa-line-chart mr-2"></i>
      New job
    <% end %>
  <% end %>
  <% if current_user.developer %>
      <a href="#" class="nav-link px-4 rounded-pill">
        <i class="fas fa-pie-chart mr-2"></i>
        Applied Jobs
      </a>
      <% if current_user.profile.present?%>
        <%= link_to profile_path(current_user.profile), class:"nav-link px-4 rounded-pill" do %>
          <i class="fas fa-user"></i>
          View Profile
        <% end %>
        <%= link_to edit_profile_path(current_user.profile), class:"nav-link px-4 rounded-pill" do %>
          <i class="fas fa-user-edit"></i>
          Edit Profile
        <% end %>
      <% end %>
  <% end %>
  <%= link_to edit_user_registration_path, class:"nav-link px-4 rounded-pill" do %>
      <i class="fas fa-edit"></i>
      Edit Account
  <% end %>
</nav>