config/routes.rb
Rails.application.routes.draw do
  resources :profiles
  resources :jobs
  root 'home#index'
  devise_for :users
  resources :conversations do
    resources :messages
   end
  get '/developers', to: "home#developers"
  mount SimpleDiscussion::Engine => "/forum"
  put 'jobs/:id/publish', to: "jobs#publish", as: "publish"
  put 'jobs/:id/unpublish', to: "jobs#unpublish", as: "unpublish"

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    jobs = Job.published
    if params[:search].present? && params[:search][:search_text].present?
      jobs = Job.search(params[:search][:search_text])
    end
    @jobs = jobs.published.desc
    # respond_to do |format|
    #   format.html
    #   format.js
    # end
  end

  def developers
    @developer = User.developer
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_result.html.erb
<div class="tr-job-posted section-padding">
  <div class="job-tab text-center">
    <ul class="nav nav-tabs justify-content-center" role="tablist">
      <li role="presentation" class="active"><a class="active show" href="#hot-jobs" aria-controls="hot-jobs" role="tab" data-toggle="tab" aria-selected="true">Hot Jobs</a></li>
      <li role="presentation"><a href="#recent-jobs" aria-controls="recent-jobs" role="tab" data-toggle="tab" class="" aria-selected="false">Recent Jobs</a></li>
      <li role="presentation"><a href="#popular-jobs" aria-controls="popular-jobs" role="tab" data-toggle="tab" class="" aria-selected="false">Popular Jobs</a></li>
    </ul>
    <div class="tab-content text-left">
      <div role="tabpanel" class="tab-pane fade active show" id="hot-jobs">
        <div class="row">
          <% @jobs.each do |job| %>	
            <div class="col-md-6 col-lg-3">
              <div class="job-item shadow-sm">
                <div class="item-overlay">
                  <div class="job-info">
                    <span class="tr-title">
                    <%= link_to job.title, job_path(job), class: "text-white" %>
                      <span><%= job.company_name%></a>
                    </span>
                      <%# <% link_to job_path(job), class: "text-white" do %> 
                      <ul class="tr-list job-meta">
                        <li><i class="fa fa-map-signs" aria-hidden="true"></i><%= job.title%></li>
                        <li><i class="fa fa-briefcase" aria-hidden="true"></i><%= job.company_name%> </li>
                        <li><i class="fas fa-dollar-sign"></i><%= number_to_currency(job.compensation_range) %></li>
                        <li><i class="fas fa-map-marker-alt"></i><%= job.headquarters%></li>
                      </ul>
                      <!--ul class="job-social tr-list">
                        <li><a href="#"><i class="far fa-heart" aria-hidden="true"></i></a></li>
                        <li><%= link_to job_path(job) do%><i class="fa fa-expand" aria-hidden="true"></i><% end %></li>
                        <li><a href="#"><i class="fa fa-bookmark" aria-hidden="true"></i></a></li>
                        <li><a href="#"><i class="fa fa-long-arrow-right" aria-hidden="true"></i></a></li>
                      </ul-->
                      <%# <% end  %>
                      <%= link_to "View Job", job_path(job), class: "btn btn-info btn-lg btn-block" %>
                    </div>			
                  </div>		
                  <div class="job-info">
                    <div class="company-logo">
                      <h3><a href="#"><%= job.title%></h3></a>
                      <span><a href="#"><%= job.company_name%> </a></span>
                    </div>
                    <%# <span class="tr-title">
                    </span> %>
                    <ul class="tr-list job-meta">
                      <li><span><i class="fa fa-briefcase" aria-hidden="true"></i></span><%= job.years_of_experience %> years of experience</li>
                      <li><span><i class="fas fa-dollar-sign"></i></span><%= number_to_currency(job.compensation_range) %></li>
                      <li><span><i class="fas fa-map-marker-alt"></i></span><%= job.headquarters%></li>
                      <li><span><i class="fas fa-browser"></i></span><%= job.company_website%></li>
                    </ul>
                    <div class="time">
                      <a href="#"><span  class="<%= job_type_color job.compensation_type%>"><%= job.compensation_type %></span></a>
                      <span class="pull-right"><%= time_ago_in_words(job.published_at) %> ago</span>
                  </div>				
                </div>
              </div>
            </div>
          <% end %>
				</div><!-- /.row -->	
			</div><!-- /.tab-pane -->
      <div role="tabpanel" class="tab-pane fade show" id="recent-jobs">
      </div>
      <div role="tabpanel" class="tab-pane fade show" id="popular-jobs">
      </div>
    </div>				
	</div><!-- /.job-tab -->			
</div>
<!--
    <% @jobs.each do |job| %>
      <div class="col-md-4">
        <div class="card shadow mb-3" id="card-profile">
          <div class="card-header text-center border-0 pt-md-4 pb-0 pb-md-4">
            <div class="d-flex justify-content-between">
              <p class="small text-muted"><%= job.published_at.strftime("%d, %b")  %></p>
              <div><a href="#" class="btn btn-sm btn-default float-right">Message</a></div>
            </div>
          </div>
           <%= link_to job_path(job), class: "text-decoration-none text-dark" do %>
          <div class="card-body pt-0">
          <div class="text-center">
              <h3>
               <%= job.title %>
              </h3>
              <div class="h5 font-weight-300">
                <%= job.company_name %>
              </div>
              <p><%= truncate(strip_tags(job.description.to_s), length: 50) %></p>
              <div class="h5 mt-4">
                  <%= job.compensation_type %>  &bull;   <%= number_to_currency(job.compensation_range) %> <br><%= job.years_of_experience %> years of experience<br>
                <% if job.remote? %>
                  Remote job
                <% end %> <% end %>
              </div>
              <div>
                <%= job.headquarters%> &bull; <%= job.company_website %>
              </div>
              <hr class="my-2">
              <%= link_to "Show more", job_path(job) %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    -->

app/views/home/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-between">
    <div>
      <h3>Recently Published Job</h3> 
    </div>
    <% if params[:search].present? %>
    <div>
      Showing Result for "<%= params[:search][:search_text]%>"
    </div>
    <% end %>
    <div>
      <%= simple_form_for(:search, url: root_url,:html => {:method => :get, :class => 'form-inline'}) do |f| %>
        <div class="input-group float-right">
        <%= f.text_field :search_text, class: 'form-control',placeholder: "Search Job or Company" %>
          <div class="input-group-btn">
            <button class="btn btn-default" type="submit">
              <i class="fa fa-search"></i>
            </button>
          </div>
        </div>&nbsp;
      <% end %>
    </div>
  </div><hr>
  <% if @jobs.present? %>
    <div id="results">
      <div class="row">
        <%= render partial: 'result' %>
      </div>
    </div>
  <% end %>
</div>  
</div>  
</div>  

app/views/home/index.js.erb
document.getElementById("results").append("<%= j render partial: 'result' %>");